import {StyleSheet} from 'react-native';
import {COLORS} from './colors';
import {FONTS} from './fonts';
import {INPUTVIEW} from './inputView';
import {Button} from './buttons';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
  },
  subText: {
    fontSize: 25,
    color: 'black',
  },
  smallText: {
    fontSize: 20,
    color: 'black',
    // alignSelf: 'center',
    // justifyContent: 'center',
    // textAlign: 'center',
  },
  roundIcon: {
    alignSelf: 'center',
    width: 70,
    height: 70,
    borderRadius: 70 / 2,
    // backgroundColor: COLORS.barColor,
    marginBottom: 10,
    // resizeMode: 'stretch'
  },
  tinyLogo: {
    width: '100%',
    height: '100%',
    alignSelf: 'center',
  },
  headerView: {
    width: '100%',
    height: 75,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#7DB0E5',
    borderBottomColor: COLORS.black,
    // borderBottomWidth: 3,
    marginBottom: 0,
    justifyContent: 'center',
  },

  headerText: {
    fontFamily: FONTS.Bold,
    fontSize: 30,
    color: COLORS.white,
    // letterSpacing: 1,
    // fontFamily: FONTS.Rubik,

    // alignSelf: 'center',
  },
  backgroundImage: {
    flex: 1,
    resizeMode: 'stretch', // or 'stretch'
  },
  headerSubView: {
    width: '50%',
    justifyContent: 'flex-end',
  },
  container: {
    flex: 1,
    backgroundColor: COLORS.main,
    marginTop: 0,
  },
  HeadStyle: {
    height: 60,
    alignContent: 'center',
    backgroundColor: 'white',
  },
  TableText: {
    margin: 10,
    fontFamily: FONTS.Medium,
  },

  smallRoundedBlueFixed: {
    backgroundColor: COLORS.blue,
    shadowColor: 'rgba(0, 0, 0, 0.2)',
    shadowOpacity: 0.8,
    elevation: 6,
    shadowRadius: 20,
    shadowOffset: {width: 3, height: 13},
    borderRadius: 5,
    width: 400,
    marginRight: 30,
    height: 65,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 7,
    marginBottom: 20,
  },
  smallText: {
    fontFamily: 'Montserrat-Medium',
    color: 'black',
    fontSize: 15,
  },
  inputViewHeight40: {
    borderWidth: 1.5,
    borderColor: COLORS.main,
    borderRadius: 25,
    width: '90%',
    height: 40,
  },
  mediumText: {
    fontFamily: 'Montserrat-Medium',
    color: 'black',
    fontSize: 25,
  },
  smallRoundedBlueRounded: {
    backgroundColor: COLORS.barColor,
    // shadowColor: 'rgba(0, 0, 0, 0.2)',
    // shadowOpacity: 0.8,
    // elevation: 6,
    // shadowRadius: 20 ,
    // shadowOffset : { width: 3, height: 13},
    borderRadius: 12,
    width: '30%',
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
    alignSelf: 'center',
  },

  smallRoundedBlueRoundedNoMargin: {
    backgroundColor: COLORS.main,
    shadowColor: 'rgba(0, 0, 0, 0.2)',
    shadowOpacity: 0.8,
    elevation: 6,
    shadowRadius: 20,
    shadowOffset: {width: 3, height: 13},
    borderRadius: 35,
    width: '40%',
    height: 45,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  cardText: {
    color: COLORS.color_grey_700,
    fontFamily: FONTS.Medium,
    fontSize: 25,
    alignSelf: 'center',
  },
  cardText30: {
    color: COLORS.main,
    fontSize: 30,
    alignSelf: 'center',
    // textDecorationLine: 'underline'
    fontFamily: FONTS.Bold,
  },
  doctorDetail: {
    width: '100%',
    backgroundColor: COLORS.white,
    height: '6%',
    marginTop: 0,
    flexDirection: 'row',
  },
  DoctorDetailText: {
    color: COLORS.black,
    fontSize: 15,
    marginLeft: 15,
  },
  inputView: {
    paddingLeft: INPUTVIEW.padding,
    borderWidth: INPUTVIEW.borderWidth,
    borderColor: '#7DB0E5',
    marginTop: INPUTVIEW.marginTop,
    borderRadius: INPUTVIEW.borderRadius,
    justifyContent: 'center',
    width: '90%',
    height: 50,
    alignSelf: 'flex-start',
  },
  inputView10: {
    padding: INPUTVIEW.padding,
    borderWidth: INPUTVIEW.borderWidth,
    borderColor: INPUTVIEW.borderColor,
    marginTop: INPUTVIEW.marginTop,
    borderRadius: INPUTVIEW.borderRadius,
    justifyContent: 'center',
    width: '7%',
    height: 40,
    alignSelf: 'flex-start',
  },
  inputViewBig: {
    borderRadius: INPUTVIEW.borderRadius,
    borderWidth: INPUTVIEW.borderWidth,
    marginTop: INPUTVIEW.marginTop,
    padding: INPUTVIEW.padding,
    width: '60%',
    height: 45,
    borderColor: INPUTVIEW.borderColor,
  },

  headingText: {
    fontSize: 30,
    fontFamily: FONTS.Bold,
  },
  cardView90: {
    width: '90%',
    height: '75%',
    backgroundColor: '#FFF',
    marginBottom: 0,
    alignSelf: 'center',
    marginTop: 10,
    borderRadius: 25,
    borderColor: 'white',
    alignItems: 'center',
  },
  inputViewCenter: {
    padding: INPUTVIEW.padding,
    borderWidth: INPUTVIEW.borderWidth,
    borderColor: INPUTVIEW.borderColor,
    marginTop: INPUTVIEW.marginTop,
    borderRadius: INPUTVIEW.borderRadius,
    justifyContent: 'center',
    width: '40%',
    height: 40,
    alignSelf: 'center',
  },
  mediumInputView: {
    padding: INPUTVIEW.padding,
    borderWidth: INPUTVIEW.borderWidth,
    borderColor: INPUTVIEW.borderColor,
    marginTop: INPUTVIEW.marginTop,
    borderRadius: INPUTVIEW.borderRadius,
    justifyContent: 'center',
    width: 400,
    height: 45,
    alignSelf: 'center',
  },
  listItem: {
    backgroundColor: COLORS.listItem,
    margin: 10,
    padding: 10,
    width: '50%',
    flex: 1,
    alignSelf: 'center',
    flexDirection: 'row',
    borderRadius: 10,
    alignItems: 'stretch',
    height: 80,

    borderColor: COLORS.barColor,
  },
  subCardView: {
    backgroundColor: COLORS.listItem,
    margin: 15,
    width: '70%',
    height: '15%',
    alignSelf: 'center',
    borderRadius: 20,
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOpacity: 0.1,
    elevation: 6,
    shadowRadius: 5,
    shadowOffset: {width: 1, height: 13},
    alignItems: 'center',
    justifyContent: 'center',
  },
  listItemBox: {
    backgroundColor: COLORS.listItem,
    margin: 10,
    width: '2%',
    height: 250,
    flex: 0.85,
    alignSelf: 'center',
    borderRadius: 15,
    padding: 15,
  },
  floating: {
    width: 80,
    height: 80,
    borderRadius: 80 / 2,
    backgroundColor: COLORS.secondary,

    justifyContent: 'center',
  },
  buttonGeneral: {
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    borderRadius: 25,
    backgroundColor: '#252726',
    height: 50,
    //  margin:50,
    width: 400,
    margin: 20,
  },
  Button_text_styling: {
    fontSize: 15,
    color: '#FFFFFF',
    //  fontWeight:'normal',
    fontFamily: 'Montserrat-Regular',
  },
  centeredText: {
    textAlign: 'center',
    fontSize: 17,
    justifyContent: 'center',
    fontFamily: FONTS.Medium,
  },
  roundIcon: {
    alignSelf: 'center',
    width: 70,
    height: 70,
    borderRadius: 70 / 2,
    // backgroundColor: COLORS.barColor,
    marginBottom: 10,
    // resizeMode: 'stretch'
  },
  roundIconSmall: {
    alignSelf: 'center',
    width: 45,
    height: 45,
    borderRadius: 45 / 2,
    // backgroundColor: COLORS.barColor,

    resizeMode: 'stretch',
  },
  dollarIcon: {
    width: 20,
    height: 20,
    marginRight: 6,
  },
  homeScreenButton: {
    backgroundColor: COLORS.white,
    borderRadius: Button.homeScrenRadius,
    width: '30%',
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    width: 320,
    height: 220,
    margin: 30,
    backgroundColor: COLORS.white,
    padding: 10,
  },
  homeScreenButtonTextContainer: {
    width: '100%',
    height: 85,
    justifyContent: 'center',
    backgroundColor: COLORS.white,
    alignSelf: 'center',
    position: 'absolute',
    bottom: 0,
    borderRadius: Button.homeScrenRadius,
  },

  tinyLogo: {
    width: '100%',
    height: '100%',
    alignSelf: 'center',
  },
  bigLogo: {
    width: 100,
    height: 100,
    borderRadius: 100 / 2,
    alignSelf: 'center',
  },
  nonRoundLogo: {
    width: 60,
    height: 60,
    alignSelf: 'flex-start',
  },
  medLogo: {
    width: 70,
    height: 70,
    borderRadius: 70 / 2,
    alignSelf: 'center',

    // resizeMode: 'stretch'
  },
  detailLogo: {
    width: 42,
    height: 42,
    borderRadius: 42 / 2,
    alignSelf: 'center',

    // resizeMode: 'stretch'
  },
  circleView: {
    alignSelf: 'center',
    width: 25,
    height: 25,
    borderRadius: 25 / 2,
    backgroundColor: COLORS.main,
    marginHorizontal: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  circleViewDisable: {
    alignSelf: 'center',
    width: 25,
    height: 25,
    borderRadius: 25 / 2,
    backgroundColor: COLORS.color_grey_400,
    marginHorizontal: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  enabled: {
    fontSize: 12,
    fontFamily: FONTS.Bold,
    color: COLORS.white,
  },
  disabled: {
    fontSize: 12,
    fontFamily: FONTS.Bold,
    color: COLORS.white,
  },
  modalView: {
    height: 250,
    width: 400,
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
  },
  button: {
    borderRadius: 20,
    padding: 10,
    elevation: 2,
    margin: 5,
    width: 80,
  },
  buttonOpen: {
    backgroundColor: '#F194FF',
  },
  mediumButton: {
    color: Button.color,
    borderRadius: Button.radius,
    width: 170,
    height: 45,
  },
  buttonClose: {
    backgroundColor: 'red',
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalText: {
    marginBottom: 15,
    textAlign: 'center',
  },
});
